// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'features/models/galpon.dart';
import 'features/models/task.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 3977530355356594612),
      name: 'Galpon',
      lastPropertyId: const IdUid(6, 4467473904833530489),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7599714052158984440),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 7981914388949632373),
            name: 'name',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 3792971474633273375),
            name: 'color',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 6223838825767705512),
            name: 'CapacidadMax',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 7914666752848216566),
            name: 'CapacidadLibre',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 4467473904833530489),
            name: 'Cuarentena',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[
        ModelBacklink(name: 'tasks', srcEntity: 'Task', srcField: '')
      ]),
  ModelEntity(
      id: const IdUid(2, 6556844354097645485),
      name: 'Task',
      lastPropertyId: const IdUid(4, 7089457599239871631),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 7990727314264509150),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 552994356631848958),
            name: 'description',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 4975807715001564612),
            name: 'completed',
            type: 1,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 7089457599239871631),
            name: 'galponId',
            type: 11,
            flags: 520,
            indexId: const IdUid(1, 1720724439705887496),
            relationTarget: 'Galpon')
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(2, 6556844354097645485),
      lastIndexId: const IdUid(1, 1720724439705887496),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Galpon: EntityDefinition<Galpon>(
        model: _entities[0],
        toOneRelations: (Galpon object) => [],
        toManyRelations: (Galpon object) => {
              RelInfo<Task>.toOneBacklink(
                      4, object.id, (Task srcObject) => srcObject.galpon):
                  object.tasks
            },
        getId: (Galpon object) => object.id,
        setId: (Galpon object, int id) {
          object.id = id;
        },
        objectToFB: (Galpon object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addInt64(2, object.color);
          fbb.addInt64(3, object.CapacidadMax);
          fbb.addInt64(4, object.CapacidadLibre);
          fbb.addBool(5, object.Cuarentena);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Galpon(
              name: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              color: const fb.Int64Reader().vTableGet(buffer, rootOffset, 8, 0),
              CapacidadMax:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..CapacidadLibre =
                const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0)
            ..Cuarentena =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 14, false);
          InternalToManyAccess.setRelInfo<Galpon>(
              object.tasks,
              store,
              RelInfo<Task>.toOneBacklink(
                  4, object.id, (Task srcObject) => srcObject.galpon));
          return object;
        }),
    Task: EntityDefinition<Task>(
        model: _entities[1],
        toOneRelations: (Task object) => [object.galpon],
        toManyRelations: (Task object) => {},
        getId: (Task object) => object.id,
        setId: (Task object, int id) {
          object.id = id;
        },
        objectToFB: (Task object, fb.Builder fbb) {
          final descriptionOffset = fbb.writeString(object.description);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, descriptionOffset);
          fbb.addBool(2, object.completed);
          fbb.addInt64(3, object.galpon.targetId);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Task(
              description: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''))
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0)
            ..completed =
                const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          object.galpon.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          object.galpon.attach(store);
          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Galpon] entity fields to define ObjectBox queries.
class Galpon_ {
  /// see [Galpon.id]
  static final id = QueryIntegerProperty<Galpon>(_entities[0].properties[0]);

  /// see [Galpon.name]
  static final name = QueryStringProperty<Galpon>(_entities[0].properties[1]);

  /// see [Galpon.color]
  static final color = QueryIntegerProperty<Galpon>(_entities[0].properties[2]);

  /// see [Galpon.CapacidadMax]
  static final CapacidadMax =
      QueryIntegerProperty<Galpon>(_entities[0].properties[3]);

  /// see [Galpon.CapacidadLibre]
  static final CapacidadLibre =
      QueryIntegerProperty<Galpon>(_entities[0].properties[4]);

  /// see [Galpon.Cuarentena]
  static final Cuarentena =
      QueryBooleanProperty<Galpon>(_entities[0].properties[5]);
}

/// [Task] entity fields to define ObjectBox queries.
class Task_ {
  /// see [Task.id]
  static final id = QueryIntegerProperty<Task>(_entities[1].properties[0]);

  /// see [Task.description]
  static final description =
      QueryStringProperty<Task>(_entities[1].properties[1]);

  /// see [Task.completed]
  static final completed =
      QueryBooleanProperty<Task>(_entities[1].properties[2]);

  /// see [Task.galpon]
  static final galpon =
      QueryRelationToOne<Task, Galpon>(_entities[1].properties[3]);
}
